# Practise session of Python

In [204]:
import os

print(os.curdir)
weight=72.67
height=1.75

.


In [143]:
bmi=weight/height**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [36]:
for i in range(1,11):
    print(" "*(11-i),end='')
    print("*"*i,end='')
    print("*"*i)

          **
         ****
        ******
       ********
      **********
     ************
    **************
   ****************
  ******************
 ********************


In [37]:
a='body mass index'
b="body mass index"


In [38]:
type(a)

str

In [39]:
type(b)

str

In [40]:
2+3

5

In [41]:
'abc'+'abc'

'abcabc'

In [42]:
"abc"+"abc"

'abcabc'

In [47]:
z=True

In [48]:
type(z)

bool

In [56]:
fam1=['rahul', 1.78, 'rohit', 1.79, 'rakhi', 1.60, 'mom', 1.60, 'dad', 1.65]

In [57]:
fam1

['rahul', 1.78, 'rohit', 1.79, 'rakhi', 1.6, 'mom', 1.6, 'dad', 1.65]

In [58]:
fam2=[['rahul', 1.78, 'rohit', 1.79, 'rakhi', 1.60, 'mom', 1.60, 'dad', 1.65]]

In [59]:
fam2

[['rahul', 1.78, 'rohit', 1.79, 'rakhi', 1.6, 'mom', 1.6, 'dad', 1.65]]

In [60]:
type(fam1)

list

In [61]:
type(fam2)

list

In [65]:
fam1[3]

1.79

In [66]:
fam1[7]

1.6

In [68]:
fam1[1:4]

[1.78, 'rohit', 1.79]

In [72]:
fam1[9]='1.80'

In [73]:
fam1

['rahul', 1.78, 'rohit', 1.79, 'rakhi', 1.6, 'mom', 1.6, 'dad', '1.80']

In [74]:
fam1[0:2]=['xyz', 5.61]

In [75]:
fam1

['xyz', 5.61, 'rohit', 1.79, 'rakhi', 1.6, 'mom', 1.6, 'dad', '1.80']

In [78]:
fam1+["w", 1.21]

['xyz',
 5.61,
 'rohit',
 1.79,
 'rakhi',
 1.6,
 'mom',
 1.6,
 'dad',
 '1.80',
 'w',
 1.21]

In [79]:
fam1

['xyz', 5.61, 'rohit', 1.79, 'rakhi', 1.6, 'mom', 1.6, 'dad', '1.80']

In [80]:
fan_ext=fam1+["w", 1.21]

In [81]:
fan_ext

['xyz',
 5.61,
 'rohit',
 1.79,
 'rakhi',
 1.6,
 'mom',
 1.6,
 'dad',
 '1.80',
 'w',
 1.21]

In [82]:
del(fam1[2])

In [83]:
fam1

['xyz', 5.61, 1.79, 'rakhi', 1.6, 'mom', 1.6, 'dad', '1.80']

In [84]:
del(fam1[3])

In [85]:
fam1

['xyz', 5.61, 1.79, 1.6, 'mom', 1.6, 'dad', '1.80']

In [88]:
x=["a","b","c"]
y=x
y[1]="z"
y

['a', 'z', 'c']

In [89]:
x

['a', 'z', 'c']

In [96]:
x=["a","b","c"]
y= list(x)
y=x[:]
y[1]="z"
y

['a', 'z', 'c']

In [97]:
x

['a', 'b', 'c']

In [99]:
fam=[1.32,1.87,1.45]

In [100]:
max(fam)

1.87

In [101]:
tallest=max(fam)


In [102]:
tallest

1.87

In [103]:
round(1.344,2)

1.34

In [104]:
round(1.445)

1

In [105]:
round(59.8)

60

In [107]:
fam1.index("mom")

4

In [109]:
fam1.count(1.79)

1

In [111]:
sister='lisa'

NameError: name 'mom' is not defined

In [113]:
rohit.capitalize()

NameError: name 'rohit' is not defined

In [115]:
sister.replace("z,"sa")

SyntaxError: invalid syntax (<ipython-input-115-414a38455e7f>, line 1)

In [116]:
fam1.append("me")

In [117]:
fam1

['xyz', 5.61, 1.79, 1.6, 'mom', 1.6, 'dad', '1.80', 'me']

In [119]:
fam1.append(1.45)

In [120]:
fam1

['xyz', 5.61, 1.79, 1.6, 'mom', 1.6, 'dad', '1.80', 'me', 1.45]

In [121]:
import numpy as np

In [123]:
array=[1,2,3,4]
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [152]:
np_height=np.array(height)
np_heightarray=([1.76,1.74,1.54])
np_weight=np.array(weight)
np_weightarray=([65.2,45.3,72.5])

In [153]:
bmi=np_weight/np_height**2

In [155]:
bmi

array([23.24380165, 23.78121284, 30.35925114])

In [156]:
bmi[1]

23.781212841854934

In [157]:
phyton_list=[1,2,3,4]
phyton_list+phyton_list

[1, 2, 3, 4, 1, 2, 3, 4]

In [159]:
numy_array=np.array([1,2,3,4])
numy_array+numy_array

array([2, 4, 6, 8])

In [160]:
bmi>23

array([ True,  True,  True])

In [163]:
bmi[bmi>24]

array([30.35925114])

In [164]:
type(np_height)

numpy.ndarray

In [178]:
np_2d=np.array([[1.32,1.43,1.54,1.65,1.45],[65.2,67.4,56.3,45.6,76.0]])

In [179]:
np_2d

array([[ 1.32,  1.43,  1.54,  1.65,  1.45],
       [65.2 , 67.4 , 56.3 , 45.6 , 76.  ]])

In [180]:
np_2d.shape

(2, 5)

In [181]:
np.mean(np_height[:,0])

IndexError: too many indices for array

In [195]:
height=np.round(np.random.normal(1.75, 0.20, 5000), 2)
weight=np.round(np.random.normal(60.32, 15, 5000), 2)

In [196]:
np_city=np.column_stack((height, weight))

In [199]:
np_city

array([[ 1.41, 33.79],
       [ 2.03, 78.69],
       [ 1.89, 72.02],
       ...,
       [ 1.49, 70.09],
       [ 1.67, 80.31],
       [ 1.73, 75.31]])

In [200]:
np.mean(np_city[:,0])

1.7512

In [201]:
np.median(np_city[:,0])

1.75

In [190]:
np.mean(np_city[:,0])

NameError: name 'np_city' is not defined

In [170]:
np_2d.shape

AttributeError: 'list' object has no attribute 'shape'

In [138]:
np_height=np.array(height)

NameError: name 'height' is not defined

In [128]:
bmi

NameError: name 'bmi' is not defined

str